export type PracticeMode = 'standard' | 'mirror' | 'harmony' | 'improvisation' | 'speed' | 'zen' | 'duet' | 'challenge';
export type DifficultyLevel = 'beginner' | 'intermediate' | 'advanced' | 'master' | 'virtuoso';
export type MelodyDifficulty = 'easy' | 'medium' | 'hard';

export interface DifficultySettings {
  melodyLength: number;
  maxGuesses: number;
  hintDelay: number;
  audioHintEnabled: boolean;
}

export const MELODY_DIFFICULTY_CONFIG: Record<MelodyDifficulty, DifficultySettings> = {
  easy: {
    melodyLength: 5,
    maxGuesses: 8,
    hintDelay: 1,
    audioHintEnabled: true,
  },
  medium: {
    melodyLength: 6,
    maxGuesses: 6,
    hintDelay: 2,
    audioHintEnabled: true,
  },
  hard: {
    melodyLength: 7,
    maxGuesses: 5,
    hintDelay: 3,
    audioHintEnabled: false,
  },
};

export const DIFFICULTY_LABELS: Record<MelodyDifficulty, { label: string; description: string; color: string; icon: string }> = {
  easy: {
    label: 'Easy',
    description: '5 notes, 8 guesses, hints available early',
    color: '#22C55E',
    icon: '🌱',
  },
  medium: {
    label: 'Medium',
    description: '6 notes, 6 guesses, standard hints',
    color: '#F59E0B',
    icon: '🎯',
  },
  hard: {
    label: 'Hard',
    description: '7+ notes, 5 guesses, no audio hints',
    color: '#EF4444',
    icon: '🔥',
  },
};

export const DIFFICULTY_STORAGE_KEY = 'melodyx_difficulty_setting';
export type SkillCategory = 'earTraining' | 'rhythm' | 'melodyRecognition' | 'noteAccuracy' | 'improvisation' | 'harmony' | 'sightReading' | 'composition' | 'theory';
export type LessonType = 'drill' | 'song' | 'theory' | 'technique' | 'creative' | 'assessment';

export interface LessonVariation {
  id: string;
  name: string;
  transform: 'transpose' | 'tempo' | 'harmony' | 'improvise' | 'mirror' | 'speed' | 'syncopate' | 'genre';
  description: string;
  modifier: number;
  unlockXp: number;
  icon: string;
}

export interface PracticeGoal {
  mode: PracticeMode;
  target: number;
  bonusXp?: number;
}

export interface Lesson {
  id: string;
  name: string;
  description: string;
  type: LessonType;
  difficulty: DifficultyLevel;
  category: string;
  skillFocus: SkillCategory[];
  targetNotes: string[];
  tempo: number;
  requiredAccuracy: number;
  xpReward: number;
  hints: string[];
  variations: LessonVariation[];
  prerequisites: string[];
  theoryTip?: string;
  videoUrl?: string;
  practiceGoals: PracticeGoal[];
  estimatedMinutes: number;
  unlockLevel?: number;
  isPremium?: boolean;
}

export interface Curriculum {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  lessons: Lesson[];
  unlockRequirement: number;
  isPremium: boolean;
  estimatedHours: number;
  skillFocus: SkillCategory[];
  difficulty: DifficultyLevel;
  category: string;
}

export interface LearningBadge {
  id: string;
  name: string;
  description: string;
  icon: string;
  requirement: {
    type: 'lessons' | 'streak' | 'perfect' | 'skill' | 'mode' | 'curriculum' | 'level' | 'xp' | 'time' | 'notes' | 'combo';
    value: number;
    skill?: SkillCategory;
    mode?: PracticeMode;
    curriculum?: string;
  };
  tier: 'bronze' | 'silver' | 'gold' | 'platinum' | 'diamond';
  xpReward: number;
}

export interface Certificate {
  id: string;
  name: string;
  description: string;
  requirements: string[];
  icon: string;
  color: string;
  isPremium: boolean;
}

export interface PowerUp {
  id: string;
  name: string;
  description: string;
  icon: string;
  effect: 'tempo_boost' | 'hint_shield' | 'harmony_helper' | 'xp_multiplier' | 'streak_saver' | 'time_freeze';
  duration: number;
  cost: number;
  unlockLevel: number;
}

export const SKILL_INFO: Record<SkillCategory, { name: string; icon: string; color: string; description: string }> = {
  earTraining: { name: 'Ear Training', icon: '👂', color: '#A78BFA', description: 'Recognize pitches and intervals by ear' },
  rhythm: { name: 'Rhythm', icon: '🥁', color: '#F59E0B', description: 'Master timing, tempo, and rhythmic patterns' },
  melodyRecognition: { name: 'Melody Recognition', icon: '🎵', color: '#22C55E', description: 'Identify and remember melodic phrases' },
  noteAccuracy: { name: 'Note Accuracy', icon: '🎯', color: '#EF4444', description: 'Hit the right notes consistently' },
  improvisation: { name: 'Improvisation', icon: '🎸', color: '#EC4899', description: 'Create music spontaneously' },
  harmony: { name: 'Harmony', icon: '🎼', color: '#06B6D4', description: 'Understand chord progressions and voicings' },
  sightReading: { name: 'Sight Reading', icon: '📖', color: '#8B5CF6', description: 'Play music at first sight' },
  composition: { name: 'Composition', icon: '✍️', color: '#10B981', description: 'Create original musical pieces' },
  theory: { name: 'Theory', icon: '📚', color: '#F97316', description: 'Understand music fundamentals' },
};

export const PRACTICE_MODE_INFO: Record<PracticeMode, { name: string; description: string; icon: string; xpBonus: number; color: string }> = {
  standard: { name: 'Standard', description: 'Listen and repeat the melody exactly', icon: '🎵', xpBonus: 1, color: '#22C55E' },
  mirror: { name: 'Mirror Mode', description: 'Play the melody in reverse order', icon: '🪞', xpBonus: 1.5, color: '#A78BFA' },
  harmony: { name: 'Harmony Builder', description: 'Add your own harmony to the melody', icon: '🎼', xpBonus: 1.75, color: '#06B6D4' },
  improvisation: { name: 'Improv Jam', description: 'Create variations on the theme', icon: '🎸', xpBonus: 2, color: '#EC4899' },
  speed: { name: 'Speed Run', description: 'Master the melody at increasing tempos', icon: '⚡', xpBonus: 1.5, color: '#F59E0B' },
  zen: { name: 'Zen Practice', description: 'Relaxed mindful practice, no time pressure', icon: '🧘', xpBonus: 1.25, color: '#10B981' },
  duet: { name: 'AI Duet', description: 'Play alongside an AI accompanist', icon: '🤝', xpBonus: 1.75, color: '#8B5CF6' },
  challenge: { name: 'Challenge Mode', description: 'Compete against the clock', icon: '🏆', xpBonus: 2.5, color: '#EF4444' },
};

export const DIFFICULTY_CONFIG: Record<DifficultyLevel, { multiplier: number; color: string; label: string }> = {
  beginner: { multiplier: 1.0, color: '#22C55E', label: 'Beginner' },
  intermediate: { multiplier: 1.5, color: '#F59E0B', label: 'Intermediate' },
  advanced: { multiplier: 2.0, color: '#EF4444', label: 'Advanced' },
  master: { multiplier: 3.0, color: '#A78BFA', label: 'Master' },
  virtuoso: { multiplier: 4.0, color: '#EC4899', label: 'Virtuoso' },
};

export const POWER_UPS: PowerUp[] = [
  { id: 'tempo_boost', name: 'Tempo Boost', description: 'Slow down playback for easier learning', icon: '🐢', effect: 'tempo_boost', duration: 60, cost: 50, unlockLevel: 3 },
  { id: 'hint_shield', name: 'Hint Shield', description: 'Get an extra hint without penalty', icon: '🛡️', effect: 'hint_shield', duration: 1, cost: 30, unlockLevel: 2 },
  { id: 'harmony_helper', name: 'Harmony Helper', description: 'AI suggests harmony notes', icon: '✨', effect: 'harmony_helper', duration: 30, cost: 75, unlockLevel: 5 },
  { id: 'xp_multiplier', name: 'XP Boost', description: 'Double XP for the next lesson', icon: '🚀', effect: 'xp_multiplier', duration: 1, cost: 100, unlockLevel: 4 },
  { id: 'streak_saver', name: 'Streak Saver', description: 'Protect your streak from one miss', icon: '🔥', effect: 'streak_saver', duration: 1, cost: 40, unlockLevel: 3 },
  { id: 'time_freeze', name: 'Time Freeze', description: 'Pause the timer in challenge mode', icon: '❄️', effect: 'time_freeze', duration: 10, cost: 60, unlockLevel: 6 },
];

export const LEARNING_BADGES: LearningBadge[] = [
  { id: 'first_lesson', name: 'First Steps', description: 'Complete your first lesson', icon: '🌟', requirement: { type: 'lessons', value: 1 }, tier: 'bronze', xpReward: 25 },
  { id: 'lessons_10', name: 'Getting Started', description: 'Complete 10 lessons', icon: '📚', requirement: { type: 'lessons', value: 10 }, tier: 'bronze', xpReward: 50 },
  { id: 'lessons_50', name: 'Dedicated Student', description: 'Complete 50 lessons', icon: '🎓', requirement: { type: 'lessons', value: 50 }, tier: 'silver', xpReward: 150 },
  { id: 'lessons_100', name: 'Century Learner', description: 'Complete 100 lessons', icon: '💯', requirement: { type: 'lessons', value: 100 }, tier: 'gold', xpReward: 300 },
  { id: 'lessons_500', name: 'Music Scholar', description: 'Complete 500 lessons', icon: '🏛️', requirement: { type: 'lessons', value: 500 }, tier: 'platinum', xpReward: 1000 },
  
  { id: 'streak_3', name: 'Three Day Streak', description: '3 day practice streak', icon: '🔥', requirement: { type: 'streak', value: 3 }, tier: 'bronze', xpReward: 30 },
  { id: 'streak_7', name: 'Week Warrior', description: '7 day practice streak', icon: '🔥', requirement: { type: 'streak', value: 7 }, tier: 'silver', xpReward: 75 },
  { id: 'streak_30', name: 'Month Master', description: '30 day practice streak', icon: '💎', requirement: { type: 'streak', value: 30 }, tier: 'gold', xpReward: 250 },
  { id: 'streak_100', name: 'Century Streak', description: '100 day practice streak', icon: '👑', requirement: { type: 'streak', value: 100 }, tier: 'diamond', xpReward: 1000 },
  { id: 'streak_365', name: 'Year of Music', description: '365 day practice streak', icon: '🌟', requirement: { type: 'streak', value: 365 }, tier: 'diamond', xpReward: 5000 },
  
  { id: 'perfect_5', name: 'Perfect Five', description: '5 lessons with 100% accuracy', icon: '🎯', requirement: { type: 'perfect', value: 5 }, tier: 'bronze', xpReward: 50 },
  { id: 'perfect_25', name: 'Precision Player', description: '25 perfect lessons', icon: '🎯', requirement: { type: 'perfect', value: 25 }, tier: 'silver', xpReward: 150 },
  { id: 'perfect_100', name: 'Flawless Maestro', description: '100 perfect lessons', icon: '💎', requirement: { type: 'perfect', value: 100 }, tier: 'gold', xpReward: 500 },
  
  { id: 'ear_5', name: 'Keen Listener', description: 'Reach level 5 in Ear Training', icon: '👂', requirement: { type: 'skill', value: 5, skill: 'earTraining' }, tier: 'bronze', xpReward: 75 },
  { id: 'ear_10', name: 'Golden Ear', description: 'Reach level 10 in Ear Training', icon: '👂', requirement: { type: 'skill', value: 10, skill: 'earTraining' }, tier: 'silver', xpReward: 200 },
  { id: 'rhythm_5', name: 'Beat Keeper', description: 'Reach level 5 in Rhythm', icon: '🥁', requirement: { type: 'skill', value: 5, skill: 'rhythm' }, tier: 'bronze', xpReward: 75 },
  { id: 'rhythm_10', name: 'Rhythm Master', description: 'Reach level 10 in Rhythm', icon: '🥁', requirement: { type: 'skill', value: 10, skill: 'rhythm' }, tier: 'silver', xpReward: 200 },
  { id: 'improv_5', name: 'Creative Spirit', description: 'Reach level 5 in Improvisation', icon: '🎸', requirement: { type: 'skill', value: 5, skill: 'improvisation' }, tier: 'silver', xpReward: 100 },
  { id: 'improv_10', name: 'Improv Star', description: 'Reach level 10 in Improvisation', icon: '🎸', requirement: { type: 'skill', value: 10, skill: 'improvisation' }, tier: 'gold', xpReward: 300 },
  { id: 'harmony_5', name: 'Harmony Seeker', description: 'Reach level 5 in Harmony', icon: '🎼', requirement: { type: 'skill', value: 5, skill: 'harmony' }, tier: 'silver', xpReward: 100 },
  { id: 'harmony_10', name: 'Harmony Hero', description: 'Reach level 10 in Harmony', icon: '🎼', requirement: { type: 'skill', value: 10, skill: 'harmony' }, tier: 'gold', xpReward: 300 },
  
  { id: 'speed_10', name: 'Quick Fingers', description: 'Complete 10 speed runs', icon: '⚡', requirement: { type: 'mode', value: 10, mode: 'speed' }, tier: 'bronze', xpReward: 75 },
  { id: 'speed_50', name: 'Speed Demon', description: 'Complete 50 speed runs', icon: '⚡', requirement: { type: 'mode', value: 50, mode: 'speed' }, tier: 'silver', xpReward: 200 },
  { id: 'mirror_10', name: 'Mirror Master', description: 'Complete 10 mirror sessions', icon: '🪞', requirement: { type: 'mode', value: 10, mode: 'mirror' }, tier: 'bronze', xpReward: 75 },
  { id: 'zen_25', name: 'Mindful Musician', description: 'Complete 25 zen sessions', icon: '🧘', requirement: { type: 'mode', value: 25, mode: 'zen' }, tier: 'silver', xpReward: 150 },
  { id: 'improv_mode_20', name: 'Jam Master', description: 'Complete 20 improv sessions', icon: '🎸', requirement: { type: 'mode', value: 20, mode: 'improvisation' }, tier: 'gold', xpReward: 250 },
  
  { id: 'level_5', name: 'Rising Star', description: 'Reach level 5', icon: '⭐', requirement: { type: 'level', value: 5 }, tier: 'bronze', xpReward: 50 },
  { id: 'level_10', name: 'Skilled Player', description: 'Reach level 10', icon: '⭐', requirement: { type: 'level', value: 10 }, tier: 'silver', xpReward: 100 },
  { id: 'level_25', name: 'Expert Musician', description: 'Reach level 25', icon: '🏆', requirement: { type: 'level', value: 25 }, tier: 'gold', xpReward: 300 },
  { id: 'level_50', name: 'Virtuoso', description: 'Reach level 50', icon: '👑', requirement: { type: 'level', value: 50 }, tier: 'platinum', xpReward: 750 },
  { id: 'level_100', name: 'Legendary', description: 'Reach level 100', icon: '🌟', requirement: { type: 'level', value: 100 }, tier: 'diamond', xpReward: 2000 },
  
  { id: 'xp_1k', name: 'Dedicated Learner', description: 'Earn 1,000 XP', icon: '📚', requirement: { type: 'xp', value: 1000 }, tier: 'bronze', xpReward: 50 },
  { id: 'xp_10k', name: 'XP Champion', description: 'Earn 10,000 XP', icon: '🏅', requirement: { type: 'xp', value: 10000 }, tier: 'silver', xpReward: 200 },
  { id: 'xp_50k', name: 'XP Legend', description: 'Earn 50,000 XP', icon: '🎖️', requirement: { type: 'xp', value: 50000 }, tier: 'gold', xpReward: 500 },
  { id: 'xp_100k', name: 'Master Musician', description: 'Earn 100,000 XP', icon: '🎓', requirement: { type: 'xp', value: 100000 }, tier: 'platinum', xpReward: 1500 },
  
  { id: 'time_1h', name: 'Hour of Practice', description: 'Practice for 1 hour total', icon: '⏱️', requirement: { type: 'time', value: 60 }, tier: 'bronze', xpReward: 25 },
  { id: 'time_10h', name: 'Dedicated Practitioner', description: 'Practice for 10 hours', icon: '⏱️', requirement: { type: 'time', value: 600 }, tier: 'silver', xpReward: 150 },
  { id: 'time_100h', name: 'Practice Makes Perfect', description: 'Practice for 100 hours', icon: '⏱️', requirement: { type: 'time', value: 6000 }, tier: 'gold', xpReward: 500 },
  
  { id: 'notes_1k', name: 'Note Collector', description: 'Play 1,000 notes', icon: '🎹', requirement: { type: 'notes', value: 1000 }, tier: 'bronze', xpReward: 30 },
  { id: 'notes_10k', name: 'Melody Maker', description: 'Play 10,000 notes', icon: '🎹', requirement: { type: 'notes', value: 10000 }, tier: 'silver', xpReward: 150 },
  { id: 'notes_100k', name: 'Symphony Creator', description: 'Play 100,000 notes', icon: '🎹', requirement: { type: 'notes', value: 100000 }, tier: 'gold', xpReward: 500 },
  
  { id: 'combo_10', name: 'Combo Starter', description: 'Achieve 10x combo', icon: '🔗', requirement: { type: 'combo', value: 10 }, tier: 'bronze', xpReward: 50 },
  { id: 'combo_25', name: 'Combo Master', description: 'Achieve 25x combo', icon: '🔗', requirement: { type: 'combo', value: 25 }, tier: 'silver', xpReward: 150 },
  { id: 'combo_50', name: 'Combo Legend', description: 'Achieve 50x combo', icon: '🔗', requirement: { type: 'combo', value: 50 }, tier: 'gold', xpReward: 300 },
];

export const CERTIFICATES: Certificate[] = [
  {
    id: 'ear_training_basic',
    name: 'Ear Training Fundamentals',
    description: 'Mastered basic pitch and interval recognition',
    requirements: ['Complete Ear Training Foundations curriculum', 'Achieve 85% average accuracy', 'Reach level 5 in Ear Training'],
    icon: '👂',
    color: '#A78BFA',
    isPremium: false,
  },
  {
    id: 'rhythm_basic',
    name: 'Rhythm Essentials',
    description: 'Demonstrated solid timing and rhythmic skills',
    requirements: ['Complete Rhythm Fundamentals curriculum', 'Complete 10 speed runs', 'Reach level 5 in Rhythm'],
    icon: '🥁',
    color: '#F59E0B',
    isPremium: false,
  },
  {
    id: 'melody_master',
    name: 'Melody Recognition Expert',
    description: 'Exceptional skill in recognizing and reproducing melodies',
    requirements: ['Complete Melody Mastery curriculum', '25 perfect melody lessons', 'Reach level 10 in Melody Recognition'],
    icon: '🎵',
    color: '#22C55E',
    isPremium: false,
  },
  {
    id: 'jazz_foundations',
    name: 'Jazz Foundations Certificate',
    description: 'Understanding of jazz theory and improvisation basics',
    requirements: ['Complete Jazz Foundations curriculum', '10 improvisation sessions', 'Reach level 5 in Improvisation'],
    icon: '🎷',
    color: '#8B5CF6',
    isPremium: true,
  },
  {
    id: 'harmony_expert',
    name: 'Harmony Expert',
    description: 'Deep understanding of harmonic structures and progressions',
    requirements: ['Complete Harmony Building curriculum', 'Reach level 10 in Harmony', '90% accuracy in harmony lessons'],
    icon: '🎼',
    color: '#06B6D4',
    isPremium: true,
  },
  {
    id: 'world_music',
    name: 'World Music Explorer',
    description: 'Appreciation and understanding of global musical traditions',
    requirements: ['Complete World Melodies curriculum', 'Perfect score on 5 world music lessons', '30 day streak'],
    icon: '🌍',
    color: '#10B981',
    isPremium: false,
  },
  {
    id: 'comprehensive_musicianship',
    name: 'Comprehensive Musicianship',
    description: 'Well-rounded musical education achievement',
    requirements: ['Complete 5 curricula', 'Reach level 25', '10,000 total XP', 'All skill categories at level 5+'],
    icon: '🎓',
    color: '#EC4899',
    isPremium: true,
  },
];

export const EXPANDED_CURRICULA: Curriculum[] = [
  {
    id: 'ear_training_foundations',
    name: 'Ear Training Foundations',
    description: 'Build your musical ear from scratch with progressive exercises. Learn to recognize pitches, intervals, and simple melodies.',
    icon: '👂',
    color: '#A78BFA',
    unlockRequirement: 0,
    isPremium: false,
    estimatedHours: 4,
    skillFocus: ['earTraining', 'noteAccuracy'],
    difficulty: 'beginner',
    category: 'Fundamentals',
    lessons: [
      {
        id: 'single_notes_1',
        name: 'Single Note Recognition',
        description: 'Listen and repeat individual notes - the foundation of ear training',
        type: 'drill',
        difficulty: 'beginner',
        category: 'Ear Training',
        skillFocus: ['earTraining', 'noteAccuracy'],
        targetNotes: ['C', 'E', 'G'],
        tempo: 800,
        requiredAccuracy: 70,
        xpReward: 50,
        estimatedMinutes: 3,
        hints: ['Start with the easiest notes', 'Listen for the pitch height', 'C is your anchor note'],
        theoryTip: 'These three notes form a C Major chord - the most fundamental chord in music!',
        prerequisites: [],
        practiceGoals: [{ mode: 'standard', target: 80 }],
        variations: [
          { id: 'transpose_up', name: 'Higher Octave', transform: 'transpose', description: 'Try one octave higher', modifier: 1, unlockXp: 100, icon: '⬆️' },
        ],
      },
      {
        id: 'simple_intervals',
        name: 'Simple Intervals',
        description: 'Learn to hear the distance between notes - the building blocks of melody',
        type: 'drill',
        difficulty: 'beginner',
        category: 'Ear Training',
        skillFocus: ['earTraining', 'melodyRecognition'],
        targetNotes: ['C', 'G'],
        tempo: 700,
        requiredAccuracy: 75,
        xpReward: 75,
        estimatedMinutes: 4,
        hints: ['A perfect fifth sounds bright', 'Think of Star Wars opening', 'The interval feels open and spacious'],
        theoryTip: 'A perfect fifth (C to G) is 7 semitones. Called "perfect" due to its pure, consonant sound.',
        prerequisites: ['single_notes_1'],
        practiceGoals: [{ mode: 'standard', target: 85 }, { mode: 'speed', target: 75 }],
        variations: [
          { id: 'octave_jump', name: 'Octave Jump', transform: 'transpose', description: 'Try one octave higher', modifier: 1, unlockXp: 150, icon: '🎵' },
          { id: 'faster', name: 'Quick Fire', transform: 'tempo', description: 'Double speed challenge', modifier: 0.5, unlockXp: 200, icon: '⚡' },
        ],
      },
      {
        id: 'three_note_patterns',
        name: 'Three Note Patterns',
        description: 'Recognize and repeat 3-note melodies with confidence',
        type: 'drill',
        difficulty: 'beginner',
        category: 'Ear Training',
        skillFocus: ['earTraining', 'melodyRecognition', 'noteAccuracy'],
        targetNotes: ['C', 'D', 'E'],
        tempo: 600,
        requiredAccuracy: 75,
        xpReward: 100,
        estimatedMinutes: 5,
        hints: ['Focus on the direction - up or down?', 'Sing along in your head', 'These notes are all neighbors'],
        theoryTip: 'C-D-E are the first three notes of the C Major scale. Moving step by step is called "stepwise motion".',
        prerequisites: ['simple_intervals'],
        practiceGoals: [{ mode: 'standard', target: 85 }, { mode: 'mirror', target: 70 }],
        variations: [
          { id: 'reverse', name: 'Mirror Mode', transform: 'mirror', description: 'Play in reverse order', modifier: -1, unlockXp: 150, icon: '🪞' },
          { id: 'add_harmony', name: 'With Harmony', transform: 'harmony', description: 'Add bass support', modifier: 1, unlockXp: 200, icon: '🎼' },
        ],
      },
      {
        id: 'ascending_scales',
        name: 'Ascending Patterns',
        description: 'Master upward melodic movement with 5-note patterns',
        type: 'drill',
        difficulty: 'beginner',
        category: 'Ear Training',
        skillFocus: ['earTraining', 'melodyRecognition'],
        targetNotes: ['C', 'D', 'E', 'F', 'G'],
        tempo: 550,
        requiredAccuracy: 75,
        xpReward: 125,
        estimatedMinutes: 5,
        hints: ['Each note is one step higher', 'Think "Do Re Mi Fa Sol"', 'Keep the rhythm steady'],
        theoryTip: 'The first 5 notes of the major scale. This pattern appears in countless melodies!',
        prerequisites: ['three_note_patterns'],
        practiceGoals: [{ mode: 'standard', target: 85 }, { mode: 'speed', target: 75 }],
        variations: [
          { id: 'speed_up', name: 'Fast Scales', transform: 'speed', description: 'Double tempo', modifier: 2, unlockXp: 200, icon: '⚡' },
        ],
      },
      {
        id: 'descending_patterns',
        name: 'Descending Patterns',
        description: 'Navigate downward melodic movements with precision',
        type: 'drill',
        difficulty: 'beginner',
        category: 'Ear Training',
        skillFocus: ['earTraining', 'melodyRecognition'],
        targetNotes: ['G', 'F', 'E', 'D', 'C'],
        tempo: 550,
        requiredAccuracy: 75,
        xpReward: 125,
        estimatedMinutes: 5,
        hints: ['Each note goes down one step', 'Like walking down stairs', 'Ending on C feels like "home"'],
        theoryTip: 'Descending scales create a sense of resolution, especially when landing on the root note.',
        prerequisites: ['ascending_scales'],
        practiceGoals: [{ mode: 'standard', target: 85 }],
        variations: [],
      },
      {
        id: 'mixed_directions',
        name: 'Mixed Directions',
        description: 'Combine ascending and descending movements',
        type: 'drill',
        difficulty: 'beginner',
        category: 'Ear Training',
        skillFocus: ['earTraining', 'melodyRecognition', 'noteAccuracy'],
        targetNotes: ['C', 'E', 'G', 'E', 'C'],
        tempo: 500,
        requiredAccuracy: 80,
        xpReward: 150,
        estimatedMinutes: 6,
        hints: ['Listen for direction changes', 'This forms an arpeggio pattern', 'The melody goes up then back down'],
        theoryTip: 'This arpeggio pattern outlines a C major chord - you\'ll hear this in countless pop songs!',
        prerequisites: ['descending_patterns'],
        practiceGoals: [{ mode: 'standard', target: 90 }, { mode: 'mirror', target: 75 }],
        variations: [],
      },
      {
        id: 'chromatic_intro',
        name: 'Chromatic Steps',
        description: 'Introduce half-step movements between notes',
        type: 'drill',
        difficulty: 'intermediate',
        category: 'Ear Training',
        skillFocus: ['earTraining', 'noteAccuracy'],
        targetNotes: ['C', 'C#', 'D', 'D#', 'E'],
        tempo: 600,
        requiredAccuracy: 75,
        xpReward: 175,
        estimatedMinutes: 7,
        hints: ['These are all half steps', 'Listen for the tension', 'The black keys are sharps'],
        theoryTip: 'The chromatic scale uses all 12 notes. It creates a sense of movement and tension.',
        prerequisites: ['mixed_directions'],
        practiceGoals: [{ mode: 'standard', target: 85 }],
        variations: [],
      },
    ],
  },
  {
    id: 'melody_mastery',
    name: 'Melody Mastery',
    description: 'Master famous melodies through focused repetition. Learn songs everyone knows and discover the theory behind them.',
    icon: '🎵',
    color: '#22C55E',
    unlockRequirement: 100,
    isPremium: false,
    estimatedHours: 6,
    skillFocus: ['melodyRecognition', 'noteAccuracy', 'rhythm'],
    difficulty: 'beginner',
    category: 'Songs',
    lessons: [
      {
        id: 'twinkle_twinkle',
        name: 'Twinkle Twinkle',
        description: 'The classic children\'s song - perfect for beginners',
        type: 'song',
        difficulty: 'beginner',
        category: 'Melody',
        skillFocus: ['melodyRecognition', 'noteAccuracy'],
        targetNotes: ['C', 'C', 'G', 'G', 'A', 'A', 'G'],
        tempo: 500,
        requiredAccuracy: 80,
        xpReward: 100,
        estimatedMinutes: 4,
        hints: ['Repeat pattern: two same notes', 'The melody ascends stepwise', 'Very recognizable - sing along!'],
        theoryTip: 'Uses only 3 different notes (C, G, A) but creates a memorable tune through repetition.',
        prerequisites: [],
        practiceGoals: [{ mode: 'standard', target: 90 }, { mode: 'harmony', target: 80 }],
        variations: [
          { id: 'faster_tempo', name: 'Faster', transform: 'tempo', description: 'Play at 1.5x speed', modifier: 1.5, unlockXp: 200, icon: '⚡' },
        ],
      },
      {
        id: 'happy_birthday',
        name: 'Happy Birthday',
        description: 'The most sung song in the world',
        type: 'song',
        difficulty: 'beginner',
        category: 'Melody',
        skillFocus: ['melodyRecognition', 'rhythm'],
        targetNotes: ['G', 'G', 'A', 'G', 'C', 'B'],
        tempo: 500,
        requiredAccuracy: 80,
        xpReward: 100,
        estimatedMinutes: 4,
        hints: ['Start with two same notes', 'The melody rises then falls', 'The jump to C is the highest point'],
        theoryTip: 'Demonstrates the power of rhythmic patterns - the repeated note at the start builds anticipation.',
        prerequisites: ['twinkle_twinkle'],
        practiceGoals: [{ mode: 'standard', target: 90 }],
        variations: [],
      },
      {
        id: 'ode_to_joy',
        name: 'Ode to Joy',
        description: 'Beethoven\'s timeless masterpiece - a stepping stone to classical',
        type: 'song',
        difficulty: 'intermediate',
        category: 'Classical',
        skillFocus: ['melodyRecognition', 'noteAccuracy', 'rhythm'],
        targetNotes: ['E', 'E', 'F', 'G', 'G', 'F', 'E', 'D'],
        tempo: 500,
        requiredAccuracy: 85,
        xpReward: 150,
        estimatedMinutes: 6,
        hints: ['Step-wise motion mostly', 'Mirror pattern in the melody', 'Notice how it goes up then comes back down'],
        theoryTip: 'Beethoven wrote this in his 9th Symphony, while completely deaf. The stepwise motion makes it singable.',
        prerequisites: ['happy_birthday'],
        practiceGoals: [{ mode: 'standard', target: 90 }, { mode: 'mirror', target: 80 }, { mode: 'harmony', target: 85 }],
        variations: [
          { id: 'mirror', name: 'Mirror Play', transform: 'mirror', description: 'Play the melody backwards', modifier: -1, unlockXp: 300, icon: '🪞' },
        ],
      },
      {
        id: 'canon_in_d',
        name: 'Canon in D Theme',
        description: 'Pachelbel\'s famous progression used in countless songs',
        type: 'song',
        difficulty: 'intermediate',
        category: 'Classical',
        skillFocus: ['melodyRecognition', 'harmony'],
        targetNotes: ['F#', 'E', 'D', 'C#', 'B', 'A', 'B', 'C#'],
        tempo: 600,
        requiredAccuracy: 80,
        xpReward: 175,
        estimatedMinutes: 7,
        hints: ['Mostly descending pattern', 'Listen for the stepwise motion', 'The last three notes turn around'],
        theoryTip: 'This piece uses a ground bass - a repeating bass pattern that hundreds of pop songs have borrowed.',
        prerequisites: ['ode_to_joy'],
        practiceGoals: [{ mode: 'standard', target: 85 }, { mode: 'harmony', target: 80 }],
        variations: [],
      },
      {
        id: 'fur_elise_intro',
        name: 'Für Elise Opening',
        description: 'The iconic opening of Beethoven\'s beloved piece',
        type: 'song',
        difficulty: 'intermediate',
        category: 'Classical',
        skillFocus: ['melodyRecognition', 'noteAccuracy'],
        targetNotes: ['E', 'D#', 'E', 'D#', 'E', 'B', 'D', 'C'],
        tempo: 450,
        requiredAccuracy: 85,
        xpReward: 200,
        estimatedMinutes: 8,
        hints: ['The first two notes repeat', 'Listen for the chromatic movement', 'The resolution is satisfying'],
        theoryTip: 'The mystery "Elise" was likely Therese Malfatti, a woman Beethoven proposed to.',
        prerequisites: ['canon_in_d'],
        practiceGoals: [{ mode: 'standard', target: 90 }, { mode: 'zen', target: 85 }],
        variations: [],
      },
    ],
  },
  {
    id: 'rhythm_fundamentals',
    name: 'Rhythm Fundamentals',
    description: 'Master timing, tempo, and rhythmic precision. Build a solid foundation for all musical performance.',
    icon: '🥁',
    color: '#F59E0B',
    unlockRequirement: 150,
    isPremium: false,
    estimatedHours: 4,
    skillFocus: ['rhythm', 'noteAccuracy'],
    difficulty: 'beginner',
    category: 'Fundamentals',
    lessons: [
      {
        id: 'steady_beat',
        name: 'Steady Beat',
        description: 'Learn to keep perfect time with quarter notes',
        type: 'drill',
        difficulty: 'beginner',
        category: 'Rhythm',
        skillFocus: ['rhythm'],
        targetNotes: ['C', 'C', 'C', 'C', 'C', 'C', 'C', 'C'],
        tempo: 600,
        requiredAccuracy: 80,
        xpReward: 75,
        estimatedMinutes: 3,
        hints: ['Keep the timing steady', 'Tap your foot to the beat', 'All notes should be evenly spaced'],
        theoryTip: 'A steady beat is the foundation of all music. Count "1-2-3-4" in your head.',
        prerequisites: [],
        practiceGoals: [{ mode: 'standard', target: 90 }],
        variations: [
          { id: 'faster', name: 'Double Time', transform: 'tempo', description: 'Twice as fast', modifier: 2, unlockXp: 150, icon: '⚡' },
        ],
      },
      {
        id: 'alternating_notes',
        name: 'Note Alternation',
        description: 'Switch between two notes while keeping rhythm',
        type: 'drill',
        difficulty: 'beginner',
        category: 'Rhythm',
        skillFocus: ['rhythm', 'noteAccuracy'],
        targetNotes: ['C', 'G', 'C', 'G', 'C', 'G', 'C', 'G'],
        tempo: 550,
        requiredAccuracy: 80,
        xpReward: 100,
        estimatedMinutes: 4,
        hints: ['Alternate evenly', 'The rhythm is as important as the notes', 'Think "low-high-low-high"'],
        theoryTip: 'Alternating bass patterns like this are the foundation of many musical styles.',
        prerequisites: ['steady_beat'],
        practiceGoals: [{ mode: 'standard', target: 90 }, { mode: 'speed', target: 80 }],
        variations: [],
      },
      {
        id: 'syncopation_intro',
        name: 'Intro to Syncopation',
        description: 'Learn off-beat accents that make music groove',
        type: 'drill',
        difficulty: 'intermediate',
        category: 'Rhythm',
        skillFocus: ['rhythm'],
        targetNotes: ['C', 'E', 'G', 'C', 'E', 'G'],
        tempo: 450,
        requiredAccuracy: 75,
        xpReward: 150,
        estimatedMinutes: 6,
        hints: ['Accent the off-beats', 'Feel the groove', 'The unexpected timing creates energy'],
        theoryTip: 'Syncopation is when emphasis falls on unexpected beats. It\'s what makes funk and jazz feel alive!',
        prerequisites: ['alternating_notes'],
        practiceGoals: [{ mode: 'standard', target: 85 }],
        variations: [],
      },
      {
        id: 'triplet_feel',
        name: 'Triplet Feel',
        description: 'Divide beats into three equal parts',
        type: 'drill',
        difficulty: 'intermediate',
        category: 'Rhythm',
        skillFocus: ['rhythm'],
        targetNotes: ['C', 'E', 'G', 'C', 'E', 'G', 'C', 'E', 'G'],
        tempo: 500,
        requiredAccuracy: 75,
        xpReward: 175,
        estimatedMinutes: 7,
        hints: ['Think "tri-puh-let"', 'All three notes are equal length', 'This creates a swing feel'],
        theoryTip: 'Triplets divide a beat into 3 equal parts instead of 2. Essential for jazz and shuffle rhythms.',
        prerequisites: ['syncopation_intro'],
        practiceGoals: [{ mode: 'standard', target: 80 }],
        variations: [],
      },
    ],
  },
  {
    id: 'pop_hits',
    name: 'Pop Song Hooks',
    description: 'Learn catchy hooks from chart-topping hits. Master the melodies that everyone knows and loves.',
    icon: '🎤',
    color: '#EF4444',
    unlockRequirement: 250,
    isPremium: false,
    estimatedHours: 6,
    skillFocus: ['melodyRecognition', 'rhythm', 'noteAccuracy'],
    difficulty: 'intermediate',
    category: 'Pop',
    lessons: [
      {
        id: 'shape_of_you_hook',
        name: 'Shape of You',
        description: 'Ed Sheeran\'s viral tropical house hit',
        type: 'song',
        difficulty: 'intermediate',
        category: 'Pop',
        skillFocus: ['melodyRecognition', 'rhythm'],
        targetNotes: ['C#', 'C#', 'B', 'A', 'B', 'C#'],
        tempo: 450,
        requiredAccuracy: 85,
        xpReward: 150,
        estimatedMinutes: 5,
        hints: ['Syncopated rhythm', 'Minor key feeling', 'The hook is infectious because of its simplicity'],
        theoryTip: 'This song uses a minor key (C# minor) which gives it that moody, groove-heavy feel.',
        prerequisites: [],
        practiceGoals: [{ mode: 'standard', target: 90 }, { mode: 'speed', target: 80 }],
        variations: [],
      },
      {
        id: 'bad_guy_hook',
        name: 'Bad Guy',
        description: 'Billie Eilish\'s signature bass-heavy hook',
        type: 'song',
        difficulty: 'intermediate',
        category: 'Pop',
        skillFocus: ['noteAccuracy', 'rhythm'],
        targetNotes: ['G', 'G', 'D#', 'D', 'D', 'A#'],
        tempo: 400,
        requiredAccuracy: 85,
        xpReward: 175,
        estimatedMinutes: 6,
        hints: ['Low, punchy notes', 'Sparse melody', 'The gaps are as important as the notes'],
        theoryTip: 'This song breaks traditional rules using unusual intervals and minimal production. Less is more!',
        prerequisites: ['shape_of_you_hook'],
        practiceGoals: [{ mode: 'standard', target: 90 }],
        variations: [],
      },
      {
        id: 'blinding_lights',
        name: 'Blinding Lights',
        description: 'The Weeknd\'s 80s-inspired synthwave anthem',
        type: 'song',
        difficulty: 'intermediate',
        category: 'Pop',
        skillFocus: ['melodyRecognition', 'rhythm'],
        targetNotes: ['F', 'D#', 'F', 'G', 'G#', 'G'],
        tempo: 420,
        requiredAccuracy: 85,
        xpReward: 175,
        estimatedMinutes: 6,
        hints: ['80s synth vibes', 'The melody bounces', 'Notice the chromatic movement'],
        theoryTip: 'The retro sound comes from synth arpeggios and chord voicings from 80s music.',
        prerequisites: ['bad_guy_hook'],
        practiceGoals: [{ mode: 'standard', target: 90 }, { mode: 'speed', target: 85 }],
        variations: [
          { id: 'speed_run', name: 'Dance Tempo', transform: 'speed', description: 'Full BPM challenge', modifier: 1.5, unlockXp: 350, icon: '⚡' },
        ],
      },
      {
        id: 'uptown_funk',
        name: 'Uptown Funk',
        description: 'Bruno Mars\' funky worldwide hit',
        type: 'song',
        difficulty: 'intermediate',
        category: 'Funk',
        skillFocus: ['rhythm', 'melodyRecognition'],
        targetNotes: ['D', 'F', 'G', 'A', 'D', 'C'],
        tempo: 400,
        requiredAccuracy: 85,
        xpReward: 175,
        estimatedMinutes: 6,
        hints: ['Feel the funk groove', 'Brass-like punctuation', 'Syncopated rhythms'],
        theoryTip: 'Classic funk uses horn stabs and syncopated bass. This song is a masterclass in groove.',
        prerequisites: ['blinding_lights'],
        practiceGoals: [{ mode: 'standard', target: 90 }, { mode: 'improvisation', target: 70 }],
        variations: [],
      },
    ],
  },
  {
    id: 'jazz_foundations',
    name: 'Jazz Foundations',
    description: 'Learn to improvise with jazz scales and patterns. Discover the language of jazz through classic licks and progressions.',
    icon: '🎷',
    color: '#8B5CF6',
    unlockRequirement: 500,
    isPremium: true,
    estimatedHours: 10,
    skillFocus: ['improvisation', 'harmony', 'melodyRecognition'],
    difficulty: 'advanced',
    category: 'Jazz',
    lessons: [
      {
        id: 'blues_scale',
        name: 'Blues Scale',
        description: 'The foundation of jazz and blues improvisation',
        type: 'technique',
        difficulty: 'advanced',
        category: 'Jazz',
        skillFocus: ['improvisation', 'melodyRecognition'],
        targetNotes: ['C', 'D#', 'F', 'F#', 'G', 'A#', 'C'],
        tempo: 400,
        requiredAccuracy: 80,
        xpReward: 200,
        estimatedMinutes: 8,
        hints: ['Blue notes add tension', 'Feel the groove', 'The flat 5 (F#) is the secret sauce'],
        theoryTip: 'The blues scale adds "blue notes" (b3, b5, b7) to create that soulful sound.',
        prerequisites: [],
        practiceGoals: [{ mode: 'standard', target: 85 }, { mode: 'improvisation', target: 70 }],
        variations: [
          { id: 'improvise', name: 'Improvise Ending', transform: 'improvise', description: 'Create your own ending', modifier: 1, unlockXp: 400, icon: '🎸' },
        ],
      },
      {
        id: 'jazz_lick_1',
        name: 'Classic Jazz Lick',
        description: 'A timeless bebop pattern used by the masters',
        type: 'technique',
        difficulty: 'advanced',
        category: 'Jazz',
        skillFocus: ['improvisation', 'rhythm'],
        targetNotes: ['G', 'A', 'B', 'D', 'C', 'A', 'G'],
        tempo: 350,
        requiredAccuracy: 80,
        xpReward: 250,
        estimatedMinutes: 10,
        hints: ['Swing the rhythm', 'Emphasize off-beats', 'Let the notes flow naturally'],
        theoryTip: 'This lick outlines a G major arpeggio with passing tones. Jazz players learn hundreds of these.',
        prerequisites: ['blues_scale'],
        practiceGoals: [{ mode: 'standard', target: 85 }, { mode: 'speed', target: 75 }],
        variations: [],
      },
      {
        id: 'ii_v_i_pattern',
        name: 'II-V-I Progression',
        description: 'The most important chord progression in jazz',
        type: 'theory',
        difficulty: 'advanced',
        category: 'Jazz',
        skillFocus: ['harmony', 'melodyRecognition'],
        targetNotes: ['D', 'F', 'A', 'G', 'B', 'D', 'C', 'E', 'G'],
        tempo: 400,
        requiredAccuracy: 75,
        xpReward: 300,
        estimatedMinutes: 12,
        hints: ['Three chords, three arpeggios', 'This progression appears everywhere', 'Listen for the resolution'],
        theoryTip: 'The II-V-I is jazz\'s "money progression." You\'ll notice it in thousands of songs!',
        prerequisites: ['jazz_lick_1'],
        practiceGoals: [{ mode: 'standard', target: 80 }, { mode: 'harmony', target: 75 }, { mode: 'improvisation', target: 70 }],
        variations: [],
      },
      {
        id: 'minor_ii_v_i',
        name: 'Minor II-V-I',
        description: 'The minor key version of the jazz staple',
        type: 'theory',
        difficulty: 'advanced',
        category: 'Jazz',
        skillFocus: ['harmony', 'improvisation'],
        targetNotes: ['D', 'F', 'G#', 'G', 'B', 'D', 'C', 'D#', 'G'],
        tempo: 400,
        requiredAccuracy: 75,
        xpReward: 325,
        estimatedMinutes: 12,
        hints: ['Darker sound than major', 'The altered scale fits over V', 'Resolution to minor chord'],
        theoryTip: 'Minor II-V-I uses half-diminished ii and often an altered dominant V chord.',
        prerequisites: ['ii_v_i_pattern'],
        practiceGoals: [{ mode: 'standard', target: 80 }, { mode: 'improvisation', target: 75 }],
        variations: [],
      },
    ],
  },
  {
    id: 'harmony_builder',
    name: 'Harmony Building',
    description: 'Learn to hear and create harmonies. Understand how chords work together to create musical emotion.',
    icon: '🎼',
    color: '#06B6D4',
    unlockRequirement: 400,
    isPremium: true,
    estimatedHours: 8,
    skillFocus: ['harmony', 'earTraining'],
    difficulty: 'intermediate',
    category: 'Theory',
    lessons: [
      {
        id: 'thirds_harmony',
        name: 'Thirds Harmony',
        description: 'Learn the most common harmony interval',
        type: 'drill',
        difficulty: 'intermediate',
        category: 'Harmony',
        skillFocus: ['harmony', 'earTraining'],
        targetNotes: ['C', 'E', 'D', 'F', 'E', 'G'],
        tempo: 550,
        requiredAccuracy: 80,
        xpReward: 150,
        estimatedMinutes: 6,
        hints: ['Each pair is a third apart', 'Major thirds sound bright', 'This is the basis of vocal harmonies'],
        theoryTip: 'A third is 4 semitones (major) or 3 semitones (minor). Most vocal harmonies use thirds.',
        prerequisites: [],
        practiceGoals: [{ mode: 'standard', target: 85 }, { mode: 'harmony', target: 80 }],
        variations: [],
      },
      {
        id: 'chord_tones',
        name: 'Chord Tones',
        description: 'Hear the notes that make up basic chords',
        type: 'theory',
        difficulty: 'intermediate',
        category: 'Harmony',
        skillFocus: ['harmony', 'melodyRecognition'],
        targetNotes: ['C', 'E', 'G', 'F', 'A', 'C', 'G', 'B', 'D'],
        tempo: 500,
        requiredAccuracy: 75,
        xpReward: 175,
        estimatedMinutes: 8,
        hints: ['Three notes form each chord', 'Listen for major vs minor', 'The root note is the "name" of the chord'],
        theoryTip: 'A chord is built by stacking thirds. C-E-G is C major (root-major third-fifth).',
        prerequisites: ['thirds_harmony'],
        practiceGoals: [{ mode: 'standard', target: 85 }, { mode: 'harmony', target: 80 }],
        variations: [],
      },
      {
        id: 'major_minor',
        name: 'Major vs Minor',
        description: 'Distinguish between happy and sad chord qualities',
        type: 'drill',
        difficulty: 'intermediate',
        category: 'Harmony',
        skillFocus: ['harmony', 'earTraining'],
        targetNotes: ['C', 'E', 'G', 'C', 'D#', 'G'],
        tempo: 550,
        requiredAccuracy: 80,
        xpReward: 175,
        estimatedMinutes: 7,
        hints: ['Major sounds happy/bright', 'Minor sounds sad/dark', 'Only one note is different'],
        theoryTip: 'The only difference is the third - major has a major third, minor has a minor third.',
        prerequisites: ['chord_tones'],
        practiceGoals: [{ mode: 'standard', target: 90 }],
        variations: [],
      },
      {
        id: 'seventh_chords',
        name: 'Seventh Chords',
        description: 'Add the seventh for jazz and soul',
        type: 'theory',
        difficulty: 'advanced',
        category: 'Harmony',
        skillFocus: ['harmony', 'theory'],
        targetNotes: ['C', 'E', 'G', 'B', 'C', 'E', 'G', 'A#'],
        tempo: 500,
        requiredAccuracy: 75,
        xpReward: 225,
        estimatedMinutes: 10,
        hints: ['Add one more third on top', 'Major 7 vs Dominant 7', 'Creates richer sound'],
        theoryTip: 'Seventh chords add color. Major 7 is dreamy, Dominant 7 wants to resolve.',
        prerequisites: ['major_minor'],
        practiceGoals: [{ mode: 'standard', target: 80 }, { mode: 'harmony', target: 75 }],
        variations: [],
      },
    ],
  },
  {
    id: 'world_music',
    name: 'World Melodies',
    description: 'Explore music from around the globe. Discover unique scales, rhythms, and cultural traditions.',
    icon: '🌍',
    color: '#10B981',
    unlockRequirement: 300,
    isPremium: false,
    estimatedHours: 5,
    skillFocus: ['melodyRecognition', 'earTraining'],
    difficulty: 'intermediate',
    category: 'World',
    lessons: [
      {
        id: 'sakura_japan',
        name: 'Sakura',
        description: 'Traditional Japanese cherry blossom melody',
        type: 'song',
        difficulty: 'intermediate',
        category: 'World',
        skillFocus: ['melodyRecognition', 'earTraining'],
        targetNotes: ['D', 'D', 'F', 'D', 'D', 'F'],
        tempo: 600,
        requiredAccuracy: 85,
        xpReward: 150,
        estimatedMinutes: 5,
        hints: ['Pentatonic scale', 'Cherry blossom imagery', 'The repetition creates a meditative feel'],
        theoryTip: 'Japanese traditional music uses the "In" scale, creating its distinctive Eastern sound.',
        prerequisites: [],
        practiceGoals: [{ mode: 'standard', target: 90 }, { mode: 'zen', target: 85 }],
        variations: [],
      },
      {
        id: 'arirang_korea',
        name: 'Arirang',
        description: 'Beloved Korean folk song with deep emotional resonance',
        type: 'song',
        difficulty: 'intermediate',
        category: 'World',
        skillFocus: ['melodyRecognition', 'rhythm'],
        targetNotes: ['G', 'A', 'C', 'D', 'E', 'D'],
        tempo: 550,
        requiredAccuracy: 85,
        xpReward: 150,
        estimatedMinutes: 5,
        hints: ['Flowing melody', 'Emotional expression', 'The pentatonic scale creates a folk feel'],
        theoryTip: 'Arirang is one of Korea\'s most important cultural assets, with over 3,000 variations.',
        prerequisites: ['sakura_japan'],
        practiceGoals: [{ mode: 'standard', target: 90 }],
        variations: [],
      },
      {
        id: 'la_cucaracha',
        name: 'La Cucaracha',
        description: 'Famous Mexican folk song with infectious rhythm',
        type: 'song',
        difficulty: 'beginner',
        category: 'World',
        skillFocus: ['rhythm', 'melodyRecognition'],
        targetNotes: ['C', 'C', 'C', 'F', 'A', 'C', 'C', 'C', 'F', 'A'],
        tempo: 400,
        requiredAccuracy: 80,
        xpReward: 125,
        estimatedMinutes: 5,
        hints: ['Lively tempo', 'Repeated pattern', 'Feel the Latin rhythm'],
        theoryTip: 'The rhythm gives this simple major scale pattern its characteristic Latin flavor.',
        prerequisites: [],
        practiceGoals: [{ mode: 'standard', target: 90 }, { mode: 'speed', target: 85 }],
        variations: [],
      },
      {
        id: 'kumbaya',
        name: 'Kumbaya',
        description: 'Spiritual song from African American heritage',
        type: 'song',
        difficulty: 'beginner',
        category: 'World',
        skillFocus: ['melodyRecognition', 'harmony'],
        targetNotes: ['C', 'E', 'G', 'G', 'A', 'G', 'E'],
        tempo: 550,
        requiredAccuracy: 80,
        xpReward: 125,
        estimatedMinutes: 4,
        hints: ['Gentle and peaceful', 'Simple but moving', 'Great for harmony practice'],
        theoryTip: 'Originally a spiritual, this song has become a symbol of unity worldwide.',
        prerequisites: ['la_cucaracha'],
        practiceGoals: [{ mode: 'standard', target: 90 }, { mode: 'harmony', target: 80 }],
        variations: [],
      },
    ],
  },
  {
    id: 'game_themes',
    name: 'Game Soundtracks',
    description: 'Master iconic melodies from video games. Play the themes that defined gaming generations.',
    icon: '🎮',
    color: '#EC4899',
    unlockRequirement: 200,
    isPremium: false,
    estimatedHours: 4,
    skillFocus: ['melodyRecognition', 'noteAccuracy'],
    difficulty: 'intermediate',
    category: 'Gaming',
    lessons: [
      {
        id: 'mario_theme',
        name: 'Super Mario Bros',
        description: 'The most recognizable video game melody ever',
        type: 'song',
        difficulty: 'intermediate',
        category: 'Gaming',
        skillFocus: ['melodyRecognition', 'rhythm'],
        targetNotes: ['E', 'E', 'E', 'C', 'E', 'G'],
        tempo: 350,
        requiredAccuracy: 85,
        xpReward: 150,
        estimatedMinutes: 5,
        hints: ['Bouncy rhythm', 'The pause before the high G', 'Think of jumping for coins'],
        theoryTip: 'Koji Kondo composed this in C major - the simplest key - making it instantly memorable.',
        prerequisites: [],
        practiceGoals: [{ mode: 'standard', target: 90 }, { mode: 'speed', target: 85 }],
        variations: [],
      },
      {
        id: 'zelda_theme',
        name: 'Zelda Main Theme',
        description: 'Epic adventure theme from Hyrule',
        type: 'song',
        difficulty: 'intermediate',
        category: 'Gaming',
        skillFocus: ['melodyRecognition', 'noteAccuracy'],
        targetNotes: ['A', 'E', 'A', 'A', 'B', 'C#', 'D'],
        tempo: 400,
        requiredAccuracy: 85,
        xpReward: 175,
        estimatedMinutes: 6,
        hints: ['Heroic and adventurous', 'The rising pattern builds excitement', 'Feel the epic scale'],
        theoryTip: 'The fanfare-like pattern is common in adventure music - rising intervals suggest triumph.',
        prerequisites: ['mario_theme'],
        practiceGoals: [{ mode: 'standard', target: 90 }],
        variations: [],
      },
      {
        id: 'tetris_theme',
        name: 'Tetris Theme',
        description: 'Russian folk song made famous by Tetris',
        type: 'song',
        difficulty: 'intermediate',
        category: 'Gaming',
        skillFocus: ['melodyRecognition', 'rhythm'],
        targetNotes: ['E', 'B', 'C', 'D', 'C', 'B', 'A'],
        tempo: 350,
        requiredAccuracy: 85,
        xpReward: 175,
        estimatedMinutes: 6,
        hints: ['Minor key creates tension', 'Fast-paced like the game', 'Originally a Russian folk song'],
        theoryTip: 'This is actually "Korobeiniki," a 19th-century Russian folk song about a peddler!',
        prerequisites: ['mario_theme'],
        practiceGoals: [{ mode: 'standard', target: 90 }, { mode: 'speed', target: 85 }],
        variations: [],
      },
      {
        id: 'minecraft_sweden',
        name: 'Sweden (Minecraft)',
        description: 'The peaceful, nostalgic Minecraft theme',
        type: 'song',
        difficulty: 'intermediate',
        category: 'Gaming',
        skillFocus: ['melodyRecognition', 'harmony'],
        targetNotes: ['A', 'C', 'E', 'A', 'G', 'E', 'C'],
        tempo: 600,
        requiredAccuracy: 80,
        xpReward: 175,
        estimatedMinutes: 7,
        hints: ['Peaceful and nostalgic', 'Let notes ring', 'Arpeggio-based melody'],
        theoryTip: 'C418\'s minimalist approach creates an ambient, emotional experience.',
        prerequisites: ['zelda_theme'],
        practiceGoals: [{ mode: 'standard', target: 85 }, { mode: 'zen', target: 90 }],
        variations: [],
      },
    ],
  },
  {
    id: 'movie_themes',
    name: 'Cinema Classics',
    description: 'Play iconic themes from legendary films. Experience the music that made movie history.',
    icon: '🎬',
    color: '#F97316',
    unlockRequirement: 350,
    isPremium: false,
    estimatedHours: 5,
    skillFocus: ['melodyRecognition', 'noteAccuracy', 'rhythm'],
    difficulty: 'intermediate',
    category: 'Film',
    lessons: [
      {
        id: 'star_wars_theme',
        name: 'Star Wars Main Theme',
        description: 'John Williams\' legendary space opera fanfare',
        type: 'song',
        difficulty: 'intermediate',
        category: 'Film',
        skillFocus: ['melodyRecognition', 'rhythm'],
        targetNotes: ['G', 'G', 'G', 'C', 'G', 'F', 'E', 'D'],
        tempo: 400,
        requiredAccuracy: 85,
        xpReward: 175,
        estimatedMinutes: 6,
        hints: ['Triumphant and epic', 'The fanfare builds', 'Perfect fifth interval'],
        theoryTip: 'Williams uses brass fanfares and leitmotifs throughout the Star Wars saga.',
        prerequisites: [],
        practiceGoals: [{ mode: 'standard', target: 90 }],
        variations: [],
      },
      {
        id: 'pink_panther',
        name: 'Pink Panther Theme',
        description: 'Henry Mancini\'s slinky detective theme',
        type: 'song',
        difficulty: 'advanced',
        category: 'Film',
        skillFocus: ['melodyRecognition', 'rhythm'],
        targetNotes: ['C#', 'D', 'E', 'F', 'C#', 'D', 'E', 'C#'],
        tempo: 400,
        requiredAccuracy: 80,
        xpReward: 200,
        estimatedMinutes: 8,
        hints: ['Sneaky and playful', 'Chromatic movement', 'The saxophone sound'],
        theoryTip: 'Mancini\'s use of chromatic notes creates the sneaky, mysterious feel.',
        prerequisites: ['star_wars_theme'],
        practiceGoals: [{ mode: 'standard', target: 85 }],
        variations: [],
      },
      {
        id: 'harry_potter',
        name: 'Hedwig\'s Theme',
        description: 'The magical Harry Potter theme',
        type: 'song',
        difficulty: 'intermediate',
        category: 'Film',
        skillFocus: ['melodyRecognition', 'noteAccuracy'],
        targetNotes: ['B', 'E', 'G', 'F#', 'E', 'B', 'A', 'F#'],
        tempo: 450,
        requiredAccuracy: 85,
        xpReward: 175,
        estimatedMinutes: 6,
        hints: ['Magical and mysterious', 'The celesta sound', 'Modal mixture creates magic'],
        theoryTip: 'Williams uses the dorian mode and celesta to create the magical atmosphere.',
        prerequisites: ['star_wars_theme'],
        practiceGoals: [{ mode: 'standard', target: 90 }, { mode: 'zen', target: 85 }],
        variations: [],
      },
    ],
  },
  {
    id: 'advanced_techniques',
    name: 'Advanced Techniques',
    description: 'Master advanced musical concepts. Push your skills to the next level.',
    icon: '🎓',
    color: '#EC4899',
    unlockRequirement: 750,
    isPremium: true,
    estimatedHours: 12,
    skillFocus: ['improvisation', 'harmony', 'composition', 'theory'],
    difficulty: 'master',
    category: 'Advanced',
    lessons: [
      {
        id: 'mode_mixture',
        name: 'Modal Mixture',
        description: 'Borrow chords from parallel modes',
        type: 'theory',
        difficulty: 'master',
        category: 'Advanced',
        skillFocus: ['harmony', 'theory'],
        targetNotes: ['C', 'E', 'G', 'C', 'D#', 'G', 'F', 'G#', 'C'],
        tempo: 500,
        requiredAccuracy: 75,
        xpReward: 300,
        estimatedMinutes: 12,
        hints: ['Borrow from parallel minor', 'Creates emotional color', 'Common in pop and film music'],
        theoryTip: 'Modal mixture borrows chords from parallel modes - like using bIII or iv in a major key.',
        prerequisites: [],
        practiceGoals: [{ mode: 'standard', target: 80 }, { mode: 'harmony', target: 75 }],
        variations: [],
      },
      {
        id: 'polyrhythm_intro',
        name: 'Polyrhythm Basics',
        description: 'Play two rhythms at once',
        type: 'technique',
        difficulty: 'master',
        category: 'Advanced',
        skillFocus: ['rhythm', 'noteAccuracy'],
        targetNotes: ['C', 'E', 'C', 'G', 'E', 'C'],
        tempo: 400,
        requiredAccuracy: 70,
        xpReward: 350,
        estimatedMinutes: 15,
        hints: ['3 against 2', 'Feel both pulses', 'Common in African and Latin music'],
        theoryTip: 'Polyrhythm is the simultaneous use of two or more conflicting rhythms.',
        prerequisites: ['mode_mixture'],
        practiceGoals: [{ mode: 'standard', target: 75 }],
        variations: [],
      },
      {
        id: 'melodic_development',
        name: 'Melodic Development',
        description: 'Transform and develop melodic ideas',
        type: 'creative',
        difficulty: 'master',
        category: 'Composition',
        skillFocus: ['composition', 'improvisation'],
        targetNotes: ['C', 'D', 'E', 'E', 'D', 'C', 'C', 'E', 'G'],
        tempo: 500,
        requiredAccuracy: 70,
        xpReward: 400,
        estimatedMinutes: 15,
        hints: ['Sequence the motif', 'Invert and augment', 'Create variations'],
        theoryTip: 'Composers develop themes through sequence, inversion, augmentation, and fragmentation.',
        prerequisites: ['polyrhythm_intro'],
        practiceGoals: [{ mode: 'standard', target: 75 }, { mode: 'improvisation', target: 80 }],
        variations: [],
      },
    ],
  },
];

export const AI_COACH_PROMPTS = {
  feedback: `You are Melody, a friendly and encouraging AI music coach in the Melodyx app. 
Generate personalized, warm feedback based on the student's performance.
Be specific, encouraging, and provide actionable tips.
Keep responses concise but meaningful.`,
  
  lessonGeneration: `Generate a custom music lesson based on the user's skill levels and preferences.
Include target notes, hints, and theory tips.
Match the difficulty to their current level.`,
  
  improvisation: `Guide the student through an improvisation exercise.
Suggest notes and patterns that fit the current harmonic context.
Encourage creativity while providing musical guardrails.`,
};

export const LEARNING_MILESTONES = [
  { xp: 100, name: 'First Steps', reward: 'Unlock Practice Modes' },
  { xp: 500, name: 'Getting Started', reward: 'Unlock Speed Mode' },
  { xp: 1000, name: 'Dedicated Learner', reward: 'Unlock AI Coach' },
  { xp: 2500, name: 'Rising Musician', reward: 'Unlock Advanced Curricula' },
  { xp: 5000, name: 'Skilled Player', reward: 'Unlock Improvisation Mode' },
  { xp: 10000, name: 'Expert Musician', reward: 'Unlock Master Lessons' },
  { xp: 25000, name: 'Music Maestro', reward: 'Unlock Virtuoso Curricula' },
  { xp: 50000, name: 'Legendary', reward: 'All Features Unlocked' },
];
