export interface SongMetadata {
  id: string;
  name: string;
  artist: string;
  album?: string;
  year: number;
  genre: string;
  era: string;
  difficulty: 'easy' | 'medium' | 'hard' | 'expert';
  notes: string[];
  extendedNotes: string[];
  hint: string;
  trivia: string;
  spotifyId?: string;
  appleMusicId?: string;
  youtubeId?: string;
  coverArt?: string;
  tags: string[];
  popularity: number;
  bpm?: number;
  key?: string;
}

export interface ArtistInfo {
  name: string;
  spotifyUrl?: string;
  appleMusicUrl?: string;
  youtubeUrl?: string;
  soundCloudUrl?: string;
  tidalUrl?: string;
  amazonMusicUrl?: string;
  websiteUrl?: string;
  bio?: string;
  genres: string[];
  imageUrl?: string;
}

export const ARTIST_DATABASE: Record<string, ArtistInfo> = {
  'The Beatles': {
    name: 'The Beatles',
    spotifyUrl: 'https://open.spotify.com/artist/3WrFJ7ztbogyGnTHbHJFl2',
    appleMusicUrl: 'https://music.apple.com/artist/the-beatles/136975',
    youtubeUrl: 'https://www.youtube.com/channel/UCR0ELRhPKh9V3yN-_5XnAGg',
    bio: 'The most influential band of all time, revolutionizing popular music in the 1960s.',
    genres: ['Rock', 'Pop', 'Psychedelic'],
    imageUrl: 'https://images.unsplash.com/photo-1619983081563-430f63602796?w=400',
  },
  'Queen': {
    name: 'Queen',
    spotifyUrl: 'https://open.spotify.com/artist/1dfeR4HaWDbWqFHLkxsg1d',
    appleMusicUrl: 'https://music.apple.com/artist/queen/3296287',
    youtubeUrl: 'https://www.youtube.com/user/queenofficial',
    bio: 'British rock legends known for theatrical performances and genre-defying music.',
    genres: ['Rock', 'Arena Rock', 'Glam Rock'],
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400',
  },
  'Ed Sheeran': {
    name: 'Ed Sheeran',
    spotifyUrl: 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V',
    appleMusicUrl: 'https://music.apple.com/artist/ed-sheeran/183313439',
    youtubeUrl: 'https://www.youtube.com/user/EdSheeran',
    bio: 'Multi-award winning singer-songwriter known for heartfelt ballads and pop hits.',
    genres: ['Pop', 'Folk Pop', 'Acoustic'],
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400',
  },
  'Billie Eilish': {
    name: 'Billie Eilish',
    spotifyUrl: 'https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH',
    appleMusicUrl: 'https://music.apple.com/artist/billie-eilish/1065981054',
    youtubeUrl: 'https://www.youtube.com/channel/UCiGm_E4ZwYSHV3bcW1pnSeQ',
    bio: 'Gen Z pop icon known for whispered vocals and dark, alternative pop sound.',
    genres: ['Pop', 'Electropop', 'Alternative'],
    imageUrl: 'https://images.unsplash.com/photo-1598387993441-a364f854c3e1?w=400',
  },
  'The Weeknd': {
    name: 'The Weeknd',
    spotifyUrl: 'https://open.spotify.com/artist/1Xyo4u8uXC1ZmMpatF05PJ',
    appleMusicUrl: 'https://music.apple.com/artist/the-weeknd/479756766',
    youtubeUrl: 'https://www.youtube.com/channel/UCqhNRDQE_fqBDBwsvmT8cTg',
    bio: 'Canadian singer known for R&B vocals and 80s synth-influenced productions.',
    genres: ['R&B', 'Pop', 'Synth-pop'],
    imageUrl: 'https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=400',
  },
  'Taylor Swift': {
    name: 'Taylor Swift',
    spotifyUrl: 'https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02',
    appleMusicUrl: 'https://music.apple.com/artist/taylor-swift/159260351',
    youtubeUrl: 'https://www.youtube.com/channel/UCqECaJ8Gagnn7YCbPEzWH6g',
    bio: 'Global superstar and prolific songwriter spanning country, pop, and indie folk.',
    genres: ['Pop', 'Country', 'Folk'],
    imageUrl: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400',
  },
  'Bruno Mars': {
    name: 'Bruno Mars',
    spotifyUrl: 'https://open.spotify.com/artist/0du5cEVh5yTK9QJze8zA0C',
    appleMusicUrl: 'https://music.apple.com/artist/bruno-mars/278873078',
    youtubeUrl: 'https://www.youtube.com/channel/UCoUM-UJ7rirJYP8CQ0EIaHA',
    bio: 'Multi-talented performer known for retro-influenced pop and R&B.',
    genres: ['Pop', 'R&B', 'Funk'],
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400',
  },
  'Dua Lipa': {
    name: 'Dua Lipa',
    spotifyUrl: 'https://open.spotify.com/artist/6M2wZ9GZgrQXHCFfjv46we',
    appleMusicUrl: 'https://music.apple.com/artist/dua-lipa/1031397873',
    youtubeUrl: 'https://www.youtube.com/channel/UC-J-KZfRV8c13fOCkhXdLiQ',
    bio: 'British pop sensation known for disco-influenced dance-pop anthems.',
    genres: ['Pop', 'Dance-pop', 'Disco'],
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400',
  },
  'Michael Jackson': {
    name: 'Michael Jackson',
    spotifyUrl: 'https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm',
    appleMusicUrl: 'https://music.apple.com/artist/michael-jackson/32940',
    youtubeUrl: 'https://www.youtube.com/channel/UC5OrDvL9DscpcAstz7JnQGA',
    bio: 'The King of Pop, one of the most significant cultural figures of the 20th century.',
    genres: ['Pop', 'R&B', 'Dance'],
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400',
  },
  'Adele': {
    name: 'Adele',
    spotifyUrl: 'https://open.spotify.com/artist/4dpARuHxo51G3z768sgnrY',
    appleMusicUrl: 'https://music.apple.com/artist/adele/262836961',
    youtubeUrl: 'https://www.youtube.com/channel/UCsRM0YB_dabtEPGPTKo-gcw',
    bio: 'British powerhouse vocalist known for emotional ballads and soul-influenced pop.',
    genres: ['Pop', 'Soul', 'R&B'],
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400',
  },
};

export const EXPANDED_SONG_LIBRARY: SongMetadata[] = [
  // 60s Classics
  {
    id: 'yesterday_beatles',
    name: 'Yesterday',
    artist: 'The Beatles',
    album: 'Help!',
    year: 1965,
    genre: 'Pop',
    era: '60s',
    difficulty: 'easy',
    notes: ['F', 'E', 'D', 'C', 'D', 'E'],
    extendedNotes: ['F', 'E', 'D', 'C', 'D', 'E', 'F', 'G', 'A', 'G', 'F', 'E'],
    hint: 'All my troubles seemed so far away',
    trivia: 'Most covered song in history with over 2,200 versions recorded.',
    spotifyId: '3BQHpFgAp4l80e1XslIjNI',
    tags: ['ballad', 'acoustic', 'classic'],
    popularity: 98,
    bpm: 96,
    key: 'F major',
  },
  {
    id: 'let_it_be_beatles',
    name: 'Let It Be',
    artist: 'The Beatles',
    album: 'Let It Be',
    year: 1970,
    genre: 'Rock',
    era: '70s',
    difficulty: 'easy',
    notes: ['C', 'G', 'A', 'F', 'C', 'G'],
    extendedNotes: ['C', 'G', 'A', 'F', 'C', 'G', 'E', 'F', 'G', 'A', 'G', 'F'],
    hint: 'Speaking words of wisdom',
    trivia: 'Written by Paul McCartney after a dream about his late mother.',
    spotifyId: '7iN1s7xHE4ifF5povM6A48',
    tags: ['ballad', 'piano', 'inspirational'],
    popularity: 97,
    bpm: 76,
    key: 'C major',
  },
  
  // 70s Rock
  {
    id: 'bohemian_rhapsody_queen',
    name: 'Bohemian Rhapsody',
    artist: 'Queen',
    album: 'A Night at the Opera',
    year: 1975,
    genre: 'Rock',
    era: '70s',
    difficulty: 'hard',
    notes: ['A#', 'G', 'A#', 'F', 'D#', 'D'],
    extendedNotes: ['A#', 'G', 'A#', 'F', 'D#', 'D', 'C', 'A#', 'G', 'F', 'G', 'A#'],
    hint: 'Is this the real life? Is this just fantasy?',
    trivia: 'Took 3 weeks to record with 180 vocal overdubs.',
    spotifyId: '3z8h0TU7ReDPLIbEnYhWZb',
    tags: ['opera', 'progressive', 'epic'],
    popularity: 99,
    bpm: 72,
    key: 'Bb major',
  },
  {
    id: 'stairway_to_heaven_led_zeppelin',
    name: 'Stairway to Heaven',
    artist: 'Led Zeppelin',
    album: 'Led Zeppelin IV',
    year: 1971,
    genre: 'Rock',
    era: '70s',
    difficulty: 'medium',
    notes: ['A', 'B', 'C', 'E', 'A', 'G#'],
    extendedNotes: ['A', 'B', 'C', 'E', 'A', 'G#', 'A', 'B', 'C', 'D', 'E', 'F#'],
    hint: 'Lady buying a stairway',
    trivia: 'Never released as a single but is one of the most requested songs on radio.',
    tags: ['progressive', 'acoustic', 'epic'],
    popularity: 98,
    bpm: 63,
    key: 'A minor',
  },

  // 80s Pop
  {
    id: 'billie_jean_mj',
    name: 'Billie Jean',
    artist: 'Michael Jackson',
    album: 'Thriller',
    year: 1982,
    genre: 'Pop',
    era: '80s',
    difficulty: 'medium',
    notes: ['F#', 'F#', 'E', 'F#', 'F#', 'B'],
    extendedNotes: ['F#', 'F#', 'E', 'F#', 'F#', 'B', 'A', 'G#', 'F#', 'E', 'D#', 'E', 'F#'],
    hint: 'The kid is not my son',
    trivia: 'The song where MJ first performed the moonwalk on TV.',
    spotifyId: '7J1uxwnxfQLu4APicE5Rnj',
    tags: ['disco', 'dance', 'iconic'],
    popularity: 99,
    bpm: 117,
    key: 'F# minor',
  },
  {
    id: 'take_on_me_aha',
    name: 'Take On Me',
    artist: 'a-ha',
    album: 'Hunting High and Low',
    year: 1985,
    genre: 'Synth-pop',
    era: '80s',
    difficulty: 'medium',
    notes: ['F#', 'F#', 'D', 'B', 'B', 'E'],
    extendedNotes: ['F#', 'F#', 'D', 'B', 'B', 'E', 'E', 'E', 'G#', 'G#', 'A', 'B', 'A'],
    hint: 'I\'ll be gone in a day or two',
    trivia: 'The music video combined live action with pencil-sketch animation.',
    spotifyId: '2WfaOiMkCvy7F5fcp2zZ8L',
    tags: ['synth', 'new wave', 'iconic'],
    popularity: 97,
    bpm: 169,
    key: 'A major',
  },
  {
    id: 'sweet_child_gnr',
    name: 'Sweet Child O\' Mine',
    artist: 'Guns N\' Roses',
    album: 'Appetite for Destruction',
    year: 1987,
    genre: 'Rock',
    era: '80s',
    difficulty: 'hard',
    notes: ['D', 'D', 'E', 'G', 'A', 'G'],
    extendedNotes: ['D', 'D', 'E', 'G', 'A', 'G', 'E', 'D', 'D', 'E', 'G', 'A', 'G', 'E'],
    hint: 'She\'s got a smile that it seems to me',
    trivia: 'Slash wrote the iconic riff as a guitar warm-up exercise.',
    spotifyId: '7o2CTH4ctstm8TNelqjb51',
    tags: ['guitar', 'ballad', 'rock'],
    popularity: 98,
    bpm: 125,
    key: 'D major',
  },

  // 90s Hits
  {
    id: 'smells_like_teen_spirit_nirvana',
    name: 'Smells Like Teen Spirit',
    artist: 'Nirvana',
    album: 'Nevermind',
    year: 1991,
    genre: 'Grunge',
    era: '90s',
    difficulty: 'medium',
    notes: ['F', 'A#', 'G#', 'C#', 'F', 'A#'],
    extendedNotes: ['F', 'A#', 'G#', 'C#', 'F', 'A#', 'G#', 'C#', 'F', 'A#', 'G#', 'C#'],
    hint: 'Here we are now, entertain us',
    trivia: 'Kurt Cobain said he was trying to write the ultimate pop song.',
    spotifyId: '5ghIJDpPoe3CfHMGu71E6T',
    tags: ['grunge', 'alternative', 'iconic'],
    popularity: 99,
    bpm: 117,
    key: 'F minor',
  },
  {
    id: 'wonderwall_oasis',
    name: 'Wonderwall',
    artist: 'Oasis',
    album: '(What\'s the Story) Morning Glory?',
    year: 1995,
    genre: 'Britpop',
    era: '90s',
    difficulty: 'easy',
    notes: ['F#', 'E', 'B', 'F#', 'A', 'E'],
    extendedNotes: ['F#', 'E', 'B', 'F#', 'A', 'E', 'F#', 'G#', 'A', 'B', 'A', 'G#'],
    hint: 'Maybe you\'re gonna be the one that saves me',
    trivia: 'The most-streamed 90s song on Spotify with over 2 billion plays.',
    spotifyId: '1qPbGZqppFwLwcBC1JQ6Vr',
    tags: ['acoustic', 'britpop', 'anthem'],
    popularity: 98,
    bpm: 87,
    key: 'F# minor',
  },

  // 2000s Pop
  {
    id: 'crazy_in_love_beyonce',
    name: 'Crazy in Love',
    artist: 'Beyoncé',
    album: 'Dangerously in Love',
    year: 2003,
    genre: 'R&B',
    era: '2000s',
    difficulty: 'medium',
    notes: ['D', 'D', 'D', 'F', 'F', 'D'],
    extendedNotes: ['D', 'D', 'D', 'F', 'F', 'D', 'A', 'G', 'F', 'D', 'C', 'D'],
    hint: 'Uh oh, uh oh, uh oh',
    trivia: 'Features a brass sample from the Chi-Lites\' 1970 song.',
    spotifyId: '5IVuqXILoxVWvWEPm82Jxr',
    tags: ['dance', 'r&b', 'horn'],
    popularity: 97,
    bpm: 100,
    key: 'D minor',
  },
  {
    id: 'mr_brightside_killers',
    name: 'Mr. Brightside',
    artist: 'The Killers',
    album: 'Hot Fuss',
    year: 2003,
    genre: 'Alternative Rock',
    era: '2000s',
    difficulty: 'medium',
    notes: ['D', 'D', 'D', 'D', 'E', 'D'],
    extendedNotes: ['D', 'D', 'D', 'D', 'E', 'D', 'C#', 'B', 'A', 'G#', 'A', 'B'],
    hint: 'Coming out of my cage',
    trivia: 'Never left the UK Top 100 chart since entering in 2004.',
    spotifyId: '7oK9VyNzrYvRFo7nQEYkWN',
    tags: ['indie', 'alternative', 'anthem'],
    popularity: 98,
    bpm: 148,
    key: 'D major',
  },

  // 2010s Pop
  {
    id: 'shape_of_you_ed',
    name: 'Shape of You',
    artist: 'Ed Sheeran',
    album: '÷',
    year: 2017,
    genre: 'Pop',
    era: '2010s',
    difficulty: 'easy',
    notes: ['C#', 'C#', 'B', 'A', 'B', 'C#'],
    extendedNotes: ['C#', 'C#', 'B', 'A', 'B', 'C#', 'D', 'E', 'F#', 'E', 'D', 'C#', 'B'],
    hint: 'I\'m in love with the shape of you',
    trivia: 'First song to reach 2 billion streams on Spotify.',
    spotifyId: '7qiZfU4dY1lWllzX7mPBI3',
    tags: ['tropical', 'dance', 'pop'],
    popularity: 99,
    bpm: 96,
    key: 'C# minor',
  },
  {
    id: 'bad_guy_billie',
    name: 'Bad Guy',
    artist: 'Billie Eilish',
    album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    year: 2019,
    genre: 'Electropop',
    era: '2010s',
    difficulty: 'medium',
    notes: ['G', 'G', 'D#', 'D', 'D', 'A#'],
    extendedNotes: ['G', 'G', 'D#', 'D', 'D', 'A#', 'G', 'G', 'D#', 'D', 'C', 'A#', 'G'],
    hint: 'Duh!',
    trivia: 'Recorded in Billie\'s childhood bedroom with her brother Finneas.',
    spotifyId: '2Fxmhks0bxGSBdJ92vM42m',
    tags: ['bass', 'whisper', 'alternative'],
    popularity: 99,
    bpm: 135,
    key: 'G minor',
  },
  {
    id: 'blinding_lights_weeknd',
    name: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    year: 2020,
    genre: 'Synth-pop',
    era: '2020s',
    difficulty: 'medium',
    notes: ['F', 'D#', 'F', 'G', 'G#', 'G'],
    extendedNotes: ['F', 'D#', 'F', 'G', 'G#', 'G', 'F', 'D#', 'C', 'D#', 'F', 'G'],
    hint: 'I\'ve been tryna call',
    trivia: 'Spent the most weeks in Billboard Hot 100 history.',
    spotifyId: '0VjIjW4GlUZAMYd2vXMi3b',
    tags: ['80s', 'synth', 'retro'],
    popularity: 99,
    bpm: 171,
    key: 'F minor',
  },
  {
    id: 'uptown_funk_bruno',
    name: 'Uptown Funk',
    artist: 'Bruno Mars',
    album: 'Uptown Special',
    year: 2014,
    genre: 'Funk',
    era: '2010s',
    difficulty: 'easy',
    notes: ['D', 'F', 'G', 'A', 'D', 'C'],
    extendedNotes: ['D', 'F', 'G', 'A', 'D', 'C', 'A', 'G', 'F', 'D', 'C', 'D', 'F'],
    hint: 'Don\'t believe me, just watch',
    trivia: 'Spent 14 weeks at #1 on the Billboard Hot 100.',
    spotifyId: '32OlwWuMpZ6b0aN2RZOeMS',
    tags: ['funk', 'dance', 'brass'],
    popularity: 99,
    bpm: 115,
    key: 'D minor',
  },

  // 2020s Hits
  {
    id: 'stay_kid_laroi',
    name: 'Stay',
    artist: 'The Kid LAROI & Justin Bieber',
    album: 'F*CK LOVE 3: OVER YOU',
    year: 2021,
    genre: 'Pop',
    era: '2020s',
    difficulty: 'easy',
    notes: ['C', 'C', 'D', 'D', 'E', 'G'],
    extendedNotes: ['C', 'C', 'D', 'D', 'E', 'G', 'E', 'D', 'C', 'D', 'E', 'G'],
    hint: 'I do the same thing I told you that I never would',
    trivia: 'Broke the record for most streams in a single day on Spotify.',
    spotifyId: '5HCyWlXZPP0y6Gqq8TgA20',
    tags: ['viral', 'pop-punk', 'collaboration'],
    popularity: 98,
    bpm: 170,
    key: 'C major',
  },
  {
    id: 'levitating_dua',
    name: 'Levitating',
    artist: 'Dua Lipa',
    album: 'Future Nostalgia',
    year: 2020,
    genre: 'Disco-pop',
    era: '2020s',
    difficulty: 'easy',
    notes: ['B', 'B', 'A', 'G#', 'F#', 'E'],
    extendedNotes: ['B', 'B', 'A', 'G#', 'F#', 'E', 'F#', 'G#', 'A', 'B', 'C#', 'B'],
    hint: 'You want me, I want you, baby',
    trivia: 'Inspired by 80s disco and Olivia Newton-John\'s "Physical".',
    spotifyId: '39LLxExYz6ewLAcYrzQtmd',
    tags: ['disco', 'dance', 'retro'],
    popularity: 98,
    bpm: 103,
    key: 'B minor',
  },
  {
    id: 'anti_hero_taylor',
    name: 'Anti-Hero',
    artist: 'Taylor Swift',
    album: 'Midnights',
    year: 2022,
    genre: 'Synth-pop',
    era: '2020s',
    difficulty: 'medium',
    notes: ['E', 'E', 'E', 'G#', 'A', 'B'],
    extendedNotes: ['E', 'E', 'E', 'G#', 'A', 'B', 'C#', 'B', 'A', 'G#', 'F#', 'E'],
    hint: 'It\'s me, hi, I\'m the problem',
    trivia: 'First song by a female artist to top Billboard Global 200 for 5 weeks.',
    spotifyId: '0V3wPSX9ygBnCm8psDIegu',
    tags: ['introspective', 'synth', 'viral'],
    popularity: 99,
    bpm: 97,
    key: 'E major',
  },
  {
    id: 'as_it_was_harry',
    name: 'As It Was',
    artist: 'Harry Styles',
    album: 'Harry\'s House',
    year: 2022,
    genre: 'Synth-pop',
    era: '2020s',
    difficulty: 'easy',
    notes: ['F#', 'F#', 'E', 'D#', 'C#', 'B'],
    extendedNotes: ['F#', 'F#', 'E', 'D#', 'C#', 'B', 'C#', 'D#', 'E', 'F#', 'G#', 'F#'],
    hint: 'You know it\'s not the same as it was',
    trivia: 'Fastest song to reach 1 billion streams on Spotify in 2022.',
    spotifyId: '4LRPiXqCikLlN15c3yImP7',
    tags: ['80s', 'synth', 'nostalgic'],
    popularity: 99,
    bpm: 174,
    key: 'F# major',
  },
  {
    id: 'flowers_miley',
    name: 'Flowers',
    artist: 'Miley Cyrus',
    album: 'Endless Summer Vacation',
    year: 2023,
    genre: 'Pop',
    era: '2020s',
    difficulty: 'easy',
    notes: ['A', 'A', 'G', 'A', 'C', 'B'],
    extendedNotes: ['A', 'A', 'G', 'A', 'C', 'B', 'A', 'G', 'E', 'G', 'A', 'B'],
    hint: 'I can buy myself flowers',
    trivia: 'Broke the record for most streams in a single week on Spotify.',
    spotifyId: '3RkVtJEZ8TYFTAFz9Ns9X6',
    tags: ['empowerment', 'disco', 'breakup'],
    popularity: 99,
    bpm: 118,
    key: 'A minor',
  },

  // Classic Game Themes
  {
    id: 'mario_theme',
    name: 'Super Mario Bros Theme',
    artist: 'Koji Kondo',
    year: 1985,
    genre: 'Video Game',
    era: '80s',
    difficulty: 'medium',
    notes: ['E', 'E', 'E', 'C', 'E', 'G'],
    extendedNotes: ['E', 'E', 'E', 'C', 'E', 'G', 'G', 'C', 'G', 'E', 'A', 'B'],
    hint: 'A plumber\'s adventure begins',
    trivia: 'One of the most recognizable video game melodies ever composed.',
    tags: ['gaming', 'nintendo', 'iconic'],
    popularity: 99,
    bpm: 180,
    key: 'C major',
  },
  {
    id: 'zelda_theme',
    name: 'Legend of Zelda Theme',
    artist: 'Koji Kondo',
    year: 1986,
    genre: 'Video Game',
    era: '80s',
    difficulty: 'medium',
    notes: ['A', 'E', 'A', 'A', 'B', 'C#'],
    extendedNotes: ['A', 'E', 'A', 'A', 'B', 'C#', 'D', 'E', 'A', 'G', 'A', 'E'],
    hint: 'A hero\'s legendary adventure',
    trivia: 'The iconic overworld theme that defined adventure game music.',
    tags: ['gaming', 'nintendo', 'adventure'],
    popularity: 98,
    bpm: 150,
    key: 'A major',
  },

  // Movie Themes
  {
    id: 'star_wars_theme',
    name: 'Star Wars Main Theme',
    artist: 'John Williams',
    year: 1977,
    genre: 'Soundtrack',
    era: '70s',
    difficulty: 'medium',
    notes: ['G', 'G', 'G', 'C', 'G', 'F'],
    extendedNotes: ['G', 'G', 'G', 'C', 'G', 'F', 'E', 'D', 'C', 'G', 'F', 'E', 'D', 'C'],
    hint: 'A long time ago in a galaxy far away',
    trivia: 'Won the Academy Award for Best Original Score in 1978.',
    tags: ['orchestral', 'epic', 'iconic'],
    popularity: 99,
    bpm: 108,
    key: 'G major',
  },
  {
    id: 'pink_panther_theme',
    name: 'The Pink Panther Theme',
    artist: 'Henry Mancini',
    year: 1963,
    genre: 'Jazz',
    era: '60s',
    difficulty: 'hard',
    notes: ['C#', 'D', 'E', 'F', 'C#', 'D'],
    extendedNotes: ['C#', 'D', 'E', 'F', 'C#', 'D', 'E', 'C#', 'D', 'E', 'F', 'A', 'G'],
    hint: 'A sneaky detective theme',
    trivia: 'Originally written for the opening credits, became more famous than the movie.',
    tags: ['jazz', 'spy', 'slinky'],
    popularity: 97,
    bpm: 116,
    key: 'E minor',
  },

  // Disney Classics
  {
    id: 'let_it_go_frozen',
    name: 'Let It Go',
    artist: 'Idina Menzel',
    album: 'Frozen Soundtrack',
    year: 2013,
    genre: 'Pop',
    era: '2010s',
    difficulty: 'medium',
    notes: ['G', 'A', 'B', 'B', 'B', 'A'],
    extendedNotes: ['G', 'A', 'B', 'B', 'B', 'A', 'B', 'E', 'D', 'E', 'F#', 'G', 'A', 'B'],
    hint: 'The cold never bothered me anyway',
    trivia: 'Won Academy Award and Golden Globe for Best Original Song.',
    spotifyId: '0qcr5FMsEO85NAQjrlDRKo',
    tags: ['disney', 'power ballad', 'broadway'],
    popularity: 99,
    bpm: 137,
    key: 'Ab major',
  },
  {
    id: 'under_the_sea_mermaid',
    name: 'Under the Sea',
    artist: 'Samuel E. Wright',
    album: 'The Little Mermaid Soundtrack',
    year: 1989,
    genre: 'Calypso',
    era: '80s',
    difficulty: 'medium',
    notes: ['C', 'C', 'C', 'D', 'E', 'E'],
    extendedNotes: ['C', 'C', 'C', 'D', 'E', 'E', 'E', 'F', 'G', 'G', 'G', 'A', 'G', 'F'],
    hint: 'Life is better where it\'s wetter',
    trivia: 'Won the Academy Award for Best Original Song.',
    tags: ['disney', 'caribbean', 'upbeat'],
    popularity: 97,
    bpm: 120,
    key: 'C major',
  },

  // Classical Pieces
  {
    id: 'fur_elise_beethoven',
    name: 'Für Elise',
    artist: 'Ludwig van Beethoven',
    year: 1810,
    genre: 'Classical',
    era: 'Classical',
    difficulty: 'medium',
    notes: ['E', 'D#', 'E', 'D#', 'E', 'B'],
    extendedNotes: ['E', 'D#', 'E', 'D#', 'E', 'B', 'D', 'C', 'A', 'C', 'E', 'A', 'B'],
    hint: 'A famous Beethoven piano piece',
    trivia: 'The mysterious "Elise" was likely Therese Malfatti, a woman Beethoven proposed to.',
    tags: ['piano', 'romantic', 'classical'],
    popularity: 98,
    bpm: 80,
    key: 'A minor',
  },
  {
    id: 'moonlight_sonata_beethoven',
    name: 'Moonlight Sonata',
    artist: 'Ludwig van Beethoven',
    year: 1801,
    genre: 'Classical',
    era: 'Classical',
    difficulty: 'easy',
    notes: ['G#', 'C#', 'E', 'G#', 'C#', 'E'],
    extendedNotes: ['G#', 'C#', 'E', 'G#', 'C#', 'E', 'G#', 'C#', 'E', 'A', 'C#', 'E'],
    hint: 'Beethoven\'s most emotional piece',
    trivia: 'Beethoven himself was not fond of it, preferring his other works.',
    tags: ['piano', 'melancholy', 'classical'],
    popularity: 98,
    bpm: 60,
    key: 'C# minor',
  },

  // International Hits
  {
    id: 'despacito_fonsi',
    name: 'Despacito',
    artist: 'Luis Fonsi & Daddy Yankee',
    album: 'Vida',
    year: 2017,
    genre: 'Reggaeton',
    era: '2010s',
    difficulty: 'easy',
    notes: ['A', 'A', 'G', 'G', 'F', 'F'],
    extendedNotes: ['A', 'A', 'G', 'G', 'F', 'F', 'E', 'E', 'F', 'G', 'A', 'A', 'G'],
    hint: 'Des-pa-cito!',
    trivia: 'First Spanish-language song to hit #1 on Billboard Hot 100 since 1996.',
    spotifyId: '6habFhsOp2NvshLv26DqMb',
    tags: ['latin', 'reggaeton', 'viral'],
    popularity: 99,
    bpm: 89,
    key: 'B minor',
  },
  {
    id: 'gangnam_style_psy',
    name: 'Gangnam Style',
    artist: 'PSY',
    year: 2012,
    genre: 'K-pop',
    era: '2010s',
    difficulty: 'easy',
    notes: ['B', 'B', 'B', 'A', 'B', 'D'],
    extendedNotes: ['B', 'B', 'B', 'A', 'B', 'D', 'C#', 'B', 'A', 'G#', 'A', 'B'],
    hint: 'Oppan Gangnam Style!',
    trivia: 'First YouTube video to reach 1 billion views.',
    spotifyId: '03UrZgTINDqvnUMbbIMhql',
    tags: ['k-pop', 'viral', 'dance'],
    popularity: 98,
    bpm: 132,
    key: 'B major',
  },

  // Recent Viral Hits
  {
    id: 'heat_waves_glass',
    name: 'Heat Waves',
    artist: 'Glass Animals',
    album: 'Dreamland',
    year: 2020,
    genre: 'Indie Pop',
    era: '2020s',
    difficulty: 'easy',
    notes: ['E', 'E', 'D', 'C#', 'B', 'A'],
    extendedNotes: ['E', 'E', 'D', 'C#', 'B', 'A', 'B', 'C#', 'D', 'E', 'F#', 'E'],
    hint: 'Sometimes all I think about is you',
    trivia: 'Became a hit 2 years after release thanks to TikTok and Minecraft streamers.',
    spotifyId: '02MWAaffLxlfxAUY7c5dvx',
    tags: ['indie', 'viral', 'tiktok'],
    popularity: 98,
    bpm: 81,
    key: 'A major',
  },
  {
    id: 'drivers_license_olivia',
    name: 'Drivers License',
    artist: 'Olivia Rodrigo',
    album: 'SOUR',
    year: 2021,
    genre: 'Pop',
    era: '2020s',
    difficulty: 'medium',
    notes: ['B', 'B', 'A', 'G#', 'F#', 'E'],
    extendedNotes: ['B', 'B', 'A', 'G#', 'F#', 'E', 'F#', 'G#', 'A', 'B', 'C#', 'B'],
    hint: 'I got my driver\'s license last week',
    trivia: 'Broke Spotify\'s record for most streams in a single day by a non-holiday song.',
    spotifyId: '5wANPM4fQCJwkGd4rN57mH',
    tags: ['breakup', 'ballad', 'gen-z'],
    popularity: 99,
    bpm: 72,
    key: 'Bb major',
  },
  {
    id: 'about_damn_time_lizzo',
    name: 'About Damn Time',
    artist: 'Lizzo',
    album: 'Special',
    year: 2022,
    genre: 'Disco-pop',
    era: '2020s',
    difficulty: 'easy',
    notes: ['A', 'A', 'G', 'F#', 'E', 'D'],
    extendedNotes: ['A', 'A', 'G', 'F#', 'E', 'D', 'E', 'F#', 'G', 'A', 'B', 'A'],
    hint: 'It\'s about damn time!',
    trivia: 'Inspired a viral TikTok dance that helped it reach #1.',
    spotifyId: '3dMJOBfaflqvMO8d4rIV0z',
    tags: ['disco', 'empowerment', 'tiktok'],
    popularity: 98,
    bpm: 109,
    key: 'D major',
  },
  {
    id: 'vampire_olivia',
    name: 'Vampire',
    artist: 'Olivia Rodrigo',
    album: 'GUTS',
    year: 2023,
    genre: 'Pop Rock',
    era: '2020s',
    difficulty: 'medium',
    notes: ['D', 'D', 'E', 'F#', 'G', 'A'],
    extendedNotes: ['D', 'D', 'E', 'F#', 'G', 'A', 'B', 'A', 'G', 'F#', 'E', 'D'],
    hint: 'The way you sold me for parts',
    trivia: 'Debuted at #1 on Billboard Hot 100 with the biggest streaming week of 2023.',
    spotifyId: '1kuGVB7EU95pJObxwvfwKS',
    tags: ['breakup', 'rock', 'emotional'],
    popularity: 99,
    bpm: 138,
    key: 'D major',
  },
];

export const SONG_TAGS = [
  'viral', 'tiktok', 'ballad', 'dance', 'rock', 'pop', 'classical', 
  'gaming', 'disney', 'movie', 'latin', 'k-pop', 'hip-hop', 'r&b',
  'indie', 'alternative', 'synth', 'disco', 'funk', 'jazz', 'country',
  'electronic', 'acoustic', 'piano', 'guitar', 'brass', 'orchestral',
];

export const ERAS = ['60s', '70s', '80s', '90s', '2000s', '2010s', '2020s', 'Classical', 'Traditional'];

export const GENRES = [
  'Pop', 'Rock', 'R&B', 'Hip-Hop', 'Electronic', 'Jazz', 'Classical',
  'Country', 'Latin', 'K-pop', 'Indie', 'Alternative', 'Disco', 'Funk',
  'Soundtrack', 'Video Game', 'Musical', 'Folk', 'World',
];

export function getSongsByEra(era: string): SongMetadata[] {
  return EXPANDED_SONG_LIBRARY.filter(s => s.era === era);
}

export function getSongsByGenre(genre: string): SongMetadata[] {
  return EXPANDED_SONG_LIBRARY.filter(s => s.genre === genre);
}

export function getSongsByTag(tag: string): SongMetadata[] {
  return EXPANDED_SONG_LIBRARY.filter(s => s.tags.includes(tag));
}

export function getSongsByDifficulty(difficulty: SongMetadata['difficulty']): SongMetadata[] {
  return EXPANDED_SONG_LIBRARY.filter(s => s.difficulty === difficulty);
}

export function getRandomSong(excludeIds: string[] = []): SongMetadata {
  const available = EXPANDED_SONG_LIBRARY.filter(s => !excludeIds.includes(s.id));
  return available[Math.floor(Math.random() * available.length)];
}

export function getDailySongFromLibrary(): SongMetadata {
  const today = new Date();
  const seed = today.getFullYear() * 10000 + (today.getMonth() + 1) * 100 + today.getDate();
  const index = seed % EXPANDED_SONG_LIBRARY.length;
  return EXPANDED_SONG_LIBRARY[index];
}

export function getArtistInfo(artistName: string): ArtistInfo | null {
  return ARTIST_DATABASE[artistName] ?? null;
}

export function searchSongs(query: string): SongMetadata[] {
  const q = query.toLowerCase();
  return EXPANDED_SONG_LIBRARY.filter(s => 
    s.name.toLowerCase().includes(q) ||
    s.artist.toLowerCase().includes(q) ||
    s.genre.toLowerCase().includes(q) ||
    s.tags.some(t => t.toLowerCase().includes(q))
  );
}
